# -*- coding: utf-8 -*-
"""Copy of Airline Review Sentiment Analysis NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9M9SyWpoECpJ1xDLh2dS4xVAgWgUMA-

# Fine-tuning a model on a text classification task
Disclaimer: this code may take hours to run.
"""

import transformers
import torch

print(transformers.__version__)
print(torch.__version__)

"""## Loading the dataset"""

# Get dataset from hugging face using load_dataset
# https://huggingface.co/datasets/TCRG/airline_reviews
from datasets import load_dataset
dataset = load_dataset("TCRG/airline_reviews")

# Split train into train + validation (it was already split into train & test) .111
split_dataset = dataset["train"].train_test_split(test_size=0.111, seed=42)

# split should be 80% train, 10% validation, 10% test
dataset = {
    "train": split_dataset["train"],
    "validation": split_dataset["test"],
    "test": dataset["test"]
}

"""## Preprocessing the data

Preprocess text with transformers `Tokenizer`. Change commented out lines for DistilBERT, BERT, and RoBERTa models.
"""

from transformers import AutoTokenizer

# Uncomment desired model
model_checkpoint = "distilbert-base-uncased"
# model_checkpoint = "bert-base-uncased"
# model_checkpoint = "roberta-base"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

encoded_dataset = {}
for split in dataset:
    encoded_dataset[split] = dataset[split].map(preprocess_function, batched=True)

"""## Fine-tuning the model

Load the pretrained model and fine-tune it, use the `AutoModelForSequenceClassification` class. Specify is the # of labels as 3: positive, negative, neutral.
"""

from transformers import AutoModelForSequenceClassification

num_labels = 3

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels
)

"""Setting up metrics

"""

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro")
    }

from transformers import TrainingArguments

batch_size = 16

training_args = TrainingArguments(

    # Uncomment desired model
    output_dir="./distilbert-airline-sentiment",
    #output_dir="./bert-airline-sentiment",
    #output_dir="./roberta-airline-sentiment",

    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    push_to_hub=False
)

from transformers import Trainer, DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate()

test_results = trainer.predict(encoded_dataset["test"])
test_preds = np.argmax(test_results.predictions, axis=-1)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(encoded_dataset["test"]["label"], test_preds))
print(confusion_matrix(encoded_dataset["test"]["label"], test_preds))

# Save the fine-tuned model
trainer.save_model("./saved_airline_model")

# Save the tokenizer so the API knows how to read the text
tokenizer.save_pretrained("./saved_airline_model")

print("Transformer successfully saved!")